config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root to: 'accounts#index'

  resources :accounts do
    resources :transactions, only: %i[index new create]
    get '/ofx_import', to: 'accounts#ofx_import'
    post '/ofx_import', to: 'accounts#ofx_import_to_account'
  end

  resources :categories do
    resources :subcategories, only: %i[index new create]
  end

  resources :statistics, only: [:index]
  resources :transactions, only: %i[show edit update destroy]
  resources :subcategories, only: %i[edit update destroy]
end

app/views/shared/_accordion_filter.html.haml
#filterAccordion{'data-controller': 'accordion-icon'}
  .wallet-accordion-item
    %a#headingOne.wallet-accordion-header{"aria-controls": "collapseOne",
                                          "aria-expanded": "true",
                                          "data-bs-target": "#collapseOne",
                                          "data-bs-toggle": "collapse",
                                          type: "button",
                                          class: "wallet-accordion-button"}

      = header_title
      %i.bi.bi-caret-down-fill
    #collapseOne.accordion-collapse.collapse{"aria-labelledby": "headingOne",
                                                 "data-bs-parent": "#filterAccordion"}
      .accordion-body
        = form_tag form_tag_path, method: :get do
          %div
          - if filter_date_range
            %div
              = label_tag 'Date Range:', nil, class: 'mt-2'
              %div.d-flex.justify-content-start.gap-3.flex-wrap
                %div.d-flex.justify-content-between{style: 'min-width: 200px'}
                  = label_tag 'Start:', nil, class: 'mt-2'
                  = date_field_tag 'start_date', @start_date, class: 'form-date form-select-sm'
                %div.d-flex.justify-content-between{style: 'min-width: 200px'}
                  = label_tag 'End:', nil, class: 'mt-2'
                  = date_field_tag 'end_date', @end_date, class: 'form-date form-select-sm'
          %div.d-flex.justify-content-start.flex-wrap{style: 'column-gap: 15px'}
            - if filter_account
              %div{style:'min-width: 250px'}
                = label_tag 'Account:', nil, class: 'mt-3'
                = select_tag 'account',
                               options_from_collection_for_select(current_user.accounts.order(:name), "id", "name", @account_id),
                               prompt: 'All',
                               class: 'form-select form-select-sm'
            - if filter_payment_type
              %div{style:'min-width: 250px'}
                = label_tag 'Payment Type:', nil, class: 'mt-3'
                = select_tag 'payment_type',
                                 options_for_select([ "All", "Income", "Expense"], @payment_type),
                                 class: 'form-select form-select-sm'
            - if filter_category
              %div{style:'min-width: 250px'}
                = label_tag 'Category:', nil, class: 'mt-3'
                = select_tag 'category',
                                 options_from_collection_for_select(current_user.categories.order(:name), "id", "name", @category_id),
                                 prompt: 'All',
                                 class: 'form-select form-select-sm'
          = submit_tag 'Apply', class: 'btn btn-primary btn-sm mt-4'
          = link_to 'Reset', form_tag_path, class: 'btn btn-outline-primary btn-sm mt-4'

app/views/shared/_flashes.html.haml
- if notice
  %div.alert.alert-success.wallet-alert{role: "alert"}
    = notice
    %a.close{"aria-label": "Close", "data-bs-dismiss": "alert", type: "button"}
      %span{"aria-hidden": "true"} ×
- if alert
  %div.alert.alert-warning.wallet-alert{role: "alert"}
    = alert
    %a.close{"aria-label": "Close", "data-bs-dismiss": "alert", type: "button"}
      %span{"aria-hidden": "true"} ×

app/views/shared/_navbar.html.haml
.wallet-navbar
  .navbar-logo
    = link_to accounts_path, class: "navbar-brand", title: "My Wallets App" do
      %i.bi.bi-wallet-fill{style:'color: green'}
  .navbar-options
    - if user_signed_in?
      = link_to "", accounts_path, class: "bi bi-house-door-fill",
                                   title: "Home",
                                   style: 'color:green'
      = link_to "", statistics_path, class: "bi bi-pie-chart-fill",
                                     title: "Statistics",
                                     style: 'color:green; font-size:23px;'
      = link_to "", categories_path, class: "bi bi-folder-fill",
                                     title: "Categories",
                                     style: 'color:green'
      %li.dropdown
        %i.bi.bi-person-circle{id: "navbarDropdown",
                               title: 'User',
                               style: 'font-size:30px;color:green',
                               data: { bs_toggle: "dropdown" },
                               'aria-haspopup': true,
                               'aria-expanded': false }
        .dropdown-menu.dropdown-menu-end.default-border-radius{"aria-labelledby" => "navbarDropdown"}
          = link_to "Edit User", edit_user_registration_path, class: "dropdown-item"
          = link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item"
    - else
      %li.login-link
        = link_to "Login", new_user_session_path, class: "nav-link"