config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root to: 'accounts#index'

  resources :accounts do
    resources :transactions, only: %i[index new create]
    get '/ofx_import', to: 'accounts#ofx_import'
    post '/ofx_import', to: 'accounts#ofx_import_to_account'
  end

  resources :categories do
    resources :subcategories, only: %i[index new create]
  end

  resources :statistics, only: [:index]
  resources :transactions, only: %i[show edit update destroy]
  resources :subcategories, only: %i[edit update destroy]
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  # Associations
  belongs_to :user
  has_many :transactions
  has_many :subcategories, dependent: :destroy

  # Validations
  validates :name, length: { maximum: 20 }, presence: true
  validates :description, length: { maximum: 50 }
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :set_category, only: %i[edit update destroy]

  def index
    @categories = policy_scope(Category).order(name: :asc)
  end

  def new
    @category = current_user.categories.new
    authorize @category
  end

  def create
    @category = current_user.categories.new(categories_params)
    authorize @category
    if @category.save
      redirect_to categories_path,
                  notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @category.update(categories_params)
      redirect_to categories_path,
                  notice: 'Category was successfully updated.'
    else
      render :new
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path,
                alert: 'Category was successfully deleted.'
  end

  private

  def categories_params
    params.require(:category).permit(:name, :description)
  end

  def set_category
    @category = current_user.categories.find(params[:id])
    authorize @category
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category_row.html.haml
%tr
  %th
    - if category.subcategories.exists?
      %a{"aria-controls": "collapse#{category.id}",
         "aria-expanded": "true",
         "data-bs-target": "#collapse#{category.id}",
         "data-bs-toggle": "collapse",
         type: "button",
         class: "wallet-accordion-button"}
        %i.bi.bi-caret-down-fill{style: 'color:green'}

  %th{ scope: 'row' }
    = category.name
  %td
    = category.description
  %td
    .action-column
      = link_to '', new_category_subcategory_path(category), 'data-controller': 'turbo',
                                                             class: 'bi bi-folder-fill text-decoration-none',
                                                             title: 'Add Subcategory'
      = link_to '', edit_category_path(category), 'data-controller': 'turbo',
                                                  class: 'bi bi-pencil-fill',
                                                  title: 'Edit Category'
      = link_to '', category_path(category), data: { turbo_method: :delete,
                                                     turbo_confirm: 'Are you sure that you want to delete this category?' },
                                             class: 'bi bi-trash-fill',
                                             title: 'Delete Category'

app/views/categories/_form.html.haml
%h4 Category
= simple_form_for @category do |f|
  = f.input :name
  = f.input :description
  .form-buttons
    = link_to 'Cancel', categories_path, class: 'btn btn-outline-primary'
    = f.submit submit_text, class: 'btn btn-primary'

app/views/categories/edit.html.haml
= render 'form'

app/views/categories/edit.turbo_stream.haml
= turbo_stream.replace 'remote_modal' do
  = render partial: 'categories/form', layout: 'layouts/main_modal',
                                     locals: { title: "Update Category",
                                               submit_text: 'Update' }

app/views/categories/index.html.haml
.add-button
  %h3 Categories
  = link_to 'Add category', new_category_path, 'data-controller': 'turbo',
                                               class: 'btn btn-primary btn-sm'

-if @categories.present?
  .bg-white.main-box-shadow.default-border-radius.p-3
    %table.table{'data-controller': 'accordion-icon'}
      %thead
        %tr
          %th{ scope: 'col', style: 'width: 30px' }
          %th{ scope: 'col' }Category
          %th{ scope: 'col' }Description
          %th.text-right{ scope: 'col' }Action
      %tbody
        #accordionCategory.accordion
        - @categories.each do |category|
          = render 'category_row', category: category
          - if category.subcategories.exists?
            %tr
              %td.accordion-body.collapse.px-4{id: "collapse#{category.id}",
                                               "aria-labelledby": "heading#{category.id}",
                                               "data-bs-parent": "#accordionCategory",
                                               colspan: "4"}
                %table.table
                  %thead
                    %th Subcategory
                    %th Description
                    %th Action
                  %tbody
                    - category.subcategories.each do |subcategory|
                      = render 'subcategories/subcategory_row', subcategory: subcategory

- else
  %p (There are no categories yet.)

app/views/categories/new.html.haml
= render 'form'

app/views/categories/new.turbo_stream.haml
= turbo_stream.replace 'remote_modal' do
  = render partial: 'categories/form', layout: 'layouts/main_modal',
                                     locals: { title: "New Category",
                                               submit_text: 'Create' }