config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root to: 'accounts#index'

  resources :accounts do
    resources :transactions, only: %i[index new create]
    get '/ofx_import', to: 'accounts#ofx_import'
    post '/ofx_import', to: 'accounts#ofx_import_to_account'
  end

  resources :categories do
    resources :subcategories, only: %i[index new create]
  end

  resources :statistics, only: [:index]
  resources :transactions, only: %i[show edit update destroy]
  resources :subcategories, only: %i[edit update destroy]
end

app/controllers/transactions_controller.rb
# frozen_string_literal: true

class TransactionsController < ApplicationController
  before_action :set_account, only: %i[new create]
  before_action :set_transaction_and_account, only: %i[show edit update destroy]

  def show
    respond_to do |format|
      format.html
      format.json { render json: @transaction }
    end
  end

  def new
    @transaction = @account.transactions.new
    authorize @transaction
  end

  def create
    @transaction = @account.transactions.new(transactions_params)
    if @transaction.save
      redirect_to account_path(@account),
                  notice: 'Transaction was successfully created.'

    else
      render :new
    end
  end

  def edit; end

  def update
    if @transaction.update(transactions_params)
      redirect_to account_path(@account),
                  notice: 'Transaction was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @transaction.destroy
    redirect_to account_path(@account),
                alert: 'Transaction was successfully deleted.',
                status: :see_other
  end

  private

  def transactions_params
    params.require(:transaction).permit(:date,
                                        :name,
                                        :description,
                                        :value,
                                        :category_id,
                                        :subcategory_id)
  end

  def set_account
    @account = current_user.accounts.find(params[:account_id])
    authorize @account
  end

  def set_transaction_and_account
    @transaction = Transaction.find(params[:id])
    authorize @transaction
    @account = @transaction.account
    authorize @account
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.haml
:css
  .hide-container{
    display: none;
  }

%div{'data-controller': 'dynamic-subcategory'}
  %h4 Transaction
  = simple_form_for simple_form_path do |f|
    = f.input :date
    = f.input :name
    = f.input :description
    = f.input :value
    = f.association :category,
                    collection: current_user.categories.order(:name),
                    prompt: 'Choose a category'
    #subcategory-field.b-3.select.optional.transaction_subcategory.hide-container{'data-transaction': @transaction.id}
      %label.form-label.select.optional{for: 'transaction_subcategory_id'} Subcategory
      %select.form-select.select.optional{name: 'transaction[subcategory_id]', id: 'transaction_subcategory_id'}

    .form-buttons
      = link_to 'Cancel', account_path(@account), class: 'btn btn-outline-primary'
      = f.submit submit_text, class: 'btn btn-primary'

app/views/transactions/_transaction_card.html.haml
%div.bg-white.main-box-shadow.default-border-radius.p-3.my-3.wallet-card.default-border-radius.p-3
  %div.card-info
    %h6= transaction.name
    %div.description
      = transaction.description
    %div
      = transaction.category&.name || 'None'
      = transaction.subcategory ? ': ' + transaction.subcategory.name : ''
  %div.card-value
    %div.value{class: "#{number_class(transaction.value)}"}
      = number_to_currency(transaction.value)
    %div{style: 'min-width:60px'}
      = link_to '', edit_transaction_path(transaction), 'data-controller': 'turbo',
                                                        class: 'bi bi-pencil-fill mx-2',
                                                        title: 'Edit transaction'
      = link_to '', transaction_path(transaction), data: { turbo_method: :delete,
                                                           turbo_confirm: 'Are you sure that you want to delete this transaction?' },
                                                   class: 'bi bi-trash-fill',
                                                   title: 'Delete transaction'

app/views/transactions/_transaction_row.html.haml
%tr
  %td= nice_date(transaction.date)
  %td= transaction.name
  %td= transaction.description
  %td= transaction.category&.name || 'None'
  %td= transaction.subcategory&.name || 'None'
  %td= transaction.check_number || 'None'
  %td.text-right{class: "#{number_class(transaction.value)}"}
    = number_to_currency(transaction.value)
  %td.text-right
    = number_to_currency(transaction.account_balance)
  %td
    .action-column
      = link_to '', edit_transaction_path(transaction), 'data-controller': 'turbo',
                                                        class: 'bi bi-pencil-fill',
                                                        title: 'Edit transaction'
      = link_to '', transaction_path(transaction), data: { turbo_method: :delete,
                                                           turbo_confirm: 'Are you sure that you want to delete this transaction?' },
                                                   class: 'bi bi-trash-fill',
                                                   title: 'Delete transaction'

app/views/transactions/edit.html.haml
= render 'form'

app/views/transactions/edit.turbo_stream.haml
= turbo_stream.replace 'remote_modal' do
  = render partial: 'transactions/form', layout: 'layouts/main_modal',
                                         locals: { title: "Edit Transaction",
                                                   simple_form_path: [@transaction],
                                                   submit_text: 'Update' }

app/views/transactions/new.html.haml
= render 'form'

app/views/transactions/new.turbo_stream.haml
= turbo_stream.replace 'remote_modal' do
  = render partial: 'transactions/form', layout: 'layouts/main_modal',
                                         locals: { title: "New Transaction",
                                                   simple_form_path: [@account, @transaction],
                                                   submit_text: 'Crate' }