config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root to: 'accounts#index'

  resources :accounts do
    resources :transactions, only: %i[index new create]
    get '/ofx_import', to: 'accounts#ofx_import'
    post '/ofx_import', to: 'accounts#ofx_import_to_account'
  end

  resources :categories do
    resources :subcategories, only: %i[index new create]
  end

  resources :statistics, only: [:index]
  resources :transactions, only: %i[show edit update destroy]
  resources :subcategories, only: %i[edit update destroy]
end

app/models/account.rb
# frozen_string_literal: true

class Account < ApplicationRecord
  # Associations
  belongs_to :user
  has_many :transactions, dependent: :destroy
  # Validations
  validates :name, length: { maximum: 20 }, presence: true
  validates :description, length: { maximum: 50 }
  validates :initial_amount, numericality: true

  def balance
    initial_amount + transactions.sum(:value)
  end

  def balance_by_date(date)
    initial_amount + transactions.where('date <= :date', date:).sum(:value)
  end

  def self.collection_balance
    sum = 0.00
    all.each { |account| sum += (account.balance || 0.00) }
    sum
  end
end

app/controllers/accounts_controller.rb
# frozen_string_literal: true

class AccountsController < ApplicationController
  before_action :set_account, only: %i[show edit update destroy ofx_import ofx_import_to_account]

  def index
    @accounts = policy_scope(Account).order(:name)
    @accounts_total_balance = @accounts.collection_balance
  end

  def show
    @transactions = @account.transactions.order(date: :desc)
    set_transaction_filter(params)
    @transactions_count = @transactions.count
  end

  def new
    @account = current_user.accounts.new
    authorize @account
  end

  def create
    @account = current_user.accounts.new(accounts_params)
    authorize @account
    if @account.save
      redirect_to accounts_path,
                  notice: 'Account was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @account.update(accounts_params)
      redirect_to accounts_path,
                  notice: 'Account was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @account.destroy
    redirect_to accounts_path,
                alert: 'Account was successfully deleted.'
  end

  def ofx_import; end

  def ofx_import_to_account
    wallet_account = @account
    ofx_file = params[:account][:ofx_file]
    OFX(ofx_file) do
      account.transactions.each do |ofx_transaction|
        wallet_transaction = wallet_account.transactions.new(name: ofx_transaction.memo,
                                                             check_number: ofx_transaction.check_number,
                                                             date: ofx_transaction.posted_at,
                                                             value: ofx_transaction.amount)
        wallet_transaction.save!
      end
    end
    redirect_to account_path(@account)
  end

  private

  def accounts_params
    params.require(:account).permit(:name, :description, :initial_amount)
  end

  def set_account
    id = params[:id] || params[:account_id]
    @account = current_user.accounts.find(id)
    authorize @account
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_account_card.html.haml
%div.bg-white.main-box-shadow.default-border-radius.p-3.my-3.wallet-card.default-border-radius.p-3
  %div.card-info
    %h6= account.name
    %div
      = account.description
    %div
      Initial Amount:
      = number_to_currency(account.initial_amount)
    %div
      Balance:
      %span{class: "#{number_class(account.balance)}"}
        = number_to_currency(account.balance)
  %div.card-value
    %div{style: 'min-width:60px'}
      = link_to '', edit_account_path(account), 'data-controller': 'turbo',
                                                class: 'bi bi-pencil-fill mx-2',
                                                title: 'Edit account'
      = link_to '', account_path(account), data: { turbo_method: :delete,
                                                   turbo_confirm: 'Are you sure that you want to delete this account?' },
                                                   class: 'bi bi-trash-fill',
                                                   title: 'Delete account'
    %div
      =link_to '', account_path(account), title: 'Account transactions',
                                          class: 'bi bi-file-text-fill mx-2'

app/views/accounts/_account_row.html.haml
%tr
  %th{ scope: 'row', style: 'color:green' }= account.name
  %td= account.description
  %td.text-right{class: "#{number_class(account.initial_amount)}"}
    = number_to_currency(account.initial_amount)
  %td.text-right{class: "#{number_class(account.balance)}"}
    = number_to_currency(account.balance)
  %td
    .action-column
      = link_to '', account_path(account), title: 'Account transactions',
                                           class: 'bi bi-file-text-fill'
      = link_to '', edit_account_path(account), 'data-controller': 'turbo',
                                                class: 'bi bi-pencil-fill',
                                                title: 'Edit account'
      = link_to '', account_path(account), data: { turbo_method: :delete,
                                                   turbo_confirm: 'Are you sure that you want to delete this account with all of its records?' },
                                           class: 'bi bi-trash-fill',
                                           title: 'Delete account'

app/views/accounts/_form.html.haml
%h4 Account
= simple_form_for @account do |f|
  = f.input :name
  = f.input :description
  = f.input :initial_amount
  .form-buttons
    = link_to 'Cancel', accounts_path, class: 'btn btn-outline-primary'
    = f.submit submit_text, class: 'btn btn-primary'

app/views/accounts/_form_modal.html.haml
= turbo_frame_tag :remote_modal, target: :_top do
  .modal.fade{'data-controller': 'modal'}
    .modal-dialog.modal-dialog-centered
      .modal-content
        .modal-header
          %h5.modal-title
            = title
          %button.btn-close{type: 'button',
                            'data-bs-dismiss': 'modal',
                            'aria-label': 'Close'}
        .modal-body
          = render 'form'

app/views/accounts/_ofx_form.html.haml
%h4 OFX Importer
= simple_form_for @account, data: { turbo: false }, url: account_ofx_import_path(@account), method: :post do |f|
  %p Choose an OFX file to import transactions from:
  = f.input :ofx_file, as: :file, label: false, input_html: { accept:".ofx" }
  .form-buttons
    = link_to 'Cancel', account_path(@account), class: 'btn btn-outline-primary'
    = f.submit 'Import', class: 'btn btn-primary'

app/views/accounts/edit.html.haml
= render 'form'

app/views/accounts/edit.turbo_stream.haml
= turbo_stream.replace 'remote_modal' do
  = render partial: 'accounts/form', layout: 'layouts/main_modal',
                                     locals: { title: "Edit Account",
                                               submit_text: 'Update' }

app/views/accounts/index.html.haml
.add-button
  %h3 Accounts Overview
  = link_to 'Add Account', new_account_path, 'data-controller': 'turbo',
                                             class: 'btn btn-primary btn-sm'

-if @accounts.present?
  .bg-white.main-box-shadow.default-border-radius.p-3.wallet-lg
    %table.table
      %thead
        %tr
          %th{ scope: 'col' }Account
          %th{ scope: 'col' }Description
          %th.text-right{ scope: 'col' }Initial Amount
          %th.text-right{ scope: 'col' }Balance
          %th.text-right{ scope: 'col' }Action
      %tbody
        - @accounts.each do |account|
          = render 'account_row', account: account
      - if @accounts.count > 1
        %tfoot
          %tr
            %td{colspan:'2'}
            %th.text-right Total
            %th.text-right= number_to_currency(@accounts_total_balance)
            %td
  %div.wallet-md
    - @accounts.each do |account|
      = render 'account_card', account: account
- else
  %p (There are no accounts yet.)

app/views/accounts/new.html.haml
= render 'form'

app/views/accounts/new.turbo_stream.haml
= turbo_stream.replace 'remote_modal' do
  = render partial: 'accounts/form', layout: 'layouts/main_modal',
                                     locals: { title: "New Account",
                                               submit_text: 'Create' }

app/views/accounts/ofx_import.html.haml
.form-wrapper
  .main-form
    %h4 OFX Importer
    = simple_form_for @account, data: { turbo: false }, url: account_ofx_import_path(@account), method: :post do |f|
      %p Choose an OFX file to import transactions from:
      = f.input :ofx_file, as: :file, label: false, input_html: { accept:".ofx" }
      .form-buttons
        = link_to 'Cancel', account_path(@account), class: 'btn btn-outline-primary'
        = f.submit 'Import', class: 'btn btn-primary'

app/views/accounts/ofx_import.turbo_stream.haml
= turbo_stream.replace 'remote_modal' do
  = render partial: 'accounts/ofx_form', layout: 'layouts/main_modal',
                                         locals: { title: "OFX Importer" }

app/views/accounts/show.html.haml
.add-button
  %h3
    = link_to 'Accounts', accounts_path(@account), class: 'text-decoration-none',
                                                   title: 'Accounts overview',
                                                   style: 'color: green'
    %span= "/ #{@account.name}"
  - unless @account.transactions.present?
    .dropdown
      %button#dropdownMenuButton1.btn.btn-primary.btn-sm.dropdown-toggle{"aria-expanded": "false",
                                                                         "data-bs-toggle": "dropdown",
                                                                         type: "button"}
        Add Transaction
      %ul.dropdown-menu{"aria-labelledby":  "dropdownMenuButton1"}
        %li
          = link_to 'Manual Transaction', new_account_transaction_path(@account), 'data-controller': 'turbo',
                                                                                  class: 'dropdown-item'
        %li
          = link_to 'Import From OFX', account_ofx_import_path(@account), 'data-controller': 'turbo',
                                                                          class: 'dropdown-item'

-if @account.transactions.present?
  %br
  .bg-white.main-box-shadow.default-border-radius.p-3
    .add-button
      %h4= "Transactions (#{@transactions_count})"
      .dropdown
        %button#dropdownMenuButton1.btn.btn-primary.btn-sm.dropdown-toggle{"aria-expanded": "false",
                                                                           "data-bs-toggle": "dropdown",
                                                                           type: "button"}
          Add Transaction
        %ul.dropdown-menu{"aria-labelledby":  "dropdownMenuButton1"}
          %li
            = link_to 'Manual Transaction', new_account_transaction_path(@account), 'data-controller': 'turbo',
                                                                                    class: 'dropdown-item'
          %li
            = link_to 'Import From OFX', account_ofx_import_path(@account), 'data-controller': 'turbo',
                                                                            class: 'dropdown-item'

    %hr
    = render 'shared/accordion_filter', form_tag_path: account_path(@account),
                                        header_title: 'Filters',
                                        filter_date_range: true,
                                        filter_account: false,
                                        filter_payment_type: true,
                                        filter_category: true
    %hr.wallet-lg

    %table.table.table-hover.wallet-lg
      %thead
        %tr
          %th{ scope: 'col' }Date
          %th{ scope: 'col' }Name
          %th{ scope: 'col' }Description
          %th{ scope: 'col' }Category
          %th{ scope: 'col' }Subcategory
          %th{ scope: 'col' }Information
          %th.text-right{ scope: 'col' }Amount
          %th.text-right{ scope: 'col' }Balance
          %th.text-right{ scope: 'col' }Action
      %tbody
        - if @transactions.present?
          - @transactions.each do |transaction|
            = render 'transactions/transaction_row', transaction: transaction
        - else
          %tr
            %td.text-center{colspan: 9} (There are no transactions for this selection.)

  %div.wallet-md
    - if @transactions.present?
      - date = ''
      - previous_date = ''
      - @transactions.each do |transaction|
        - date = transaction.date
        - if date != previous_date
          %div.d-flex.justify-content-between.align-items-center.mt-4.px-2
            %h6= long_date(date)
            = number_to_currency(transaction.account.balance_by_date(date))
        = render 'transactions/transaction_card', transaction: transaction
        - previous_date = date

- else
  %p (There are no transactions yet.)